### PR TITLE
Better way to exclude file

### PR DESCRIPTION
**Pull request by BojDom**

### CODE REVIEW

**Comment by sanex3339** [comment]
Tnx, i'll chek it later today

**Comment by BojDom** [comment]
i needed regexp because my compiled files has an hash in the name. for example vendor.362236236.js
and i cannot know the exact name

**Comment by sanex3339** [comment]
Right now you can use `'vendor.*.js'`

**Comment by steveops** [comment]
Hello, am trying to exclude vendor but I cant seem to  get it to work, What am I doing wrong here?
```
new JavaScriptObfuscator({
      compact: true,
      controlFlowFlattening: true,
      controlFlowFlatteningThreshold: 0.75,
      disableConsoleOutput: true,
      rotateStringArray: true,
      stringArray: true,
      stringArrayEncoding: true,
      stringArrayThreshold: 1
    }, ['vendor.*.js'])
```

The output, `vendor.[hash].js` is obfuscated just like `app.[hash].js`

**Pull request closed without merging**
